# FedAdagrad on C2 distribution
num-server-rounds = 20
fraction-train = 1.0
fraction-evaluate = 1.0
min-train-nodes = 6
min-evaluate-nodes = 6
local-epochs = 1
learning-rate = 0.01
batch-size = 32
strategy = "FedAdagrad"
distribution = "C2"
experiment-name = "FedAdagrad_C2_npy"
num-clients = 6
data-source = "npy"
eta = 0.01
eta-l = 0.1
tau = 1e-09
