# FedAvgM on C4 distribution
num-server-rounds = 20
fraction-train = 1.0
fraction-evaluate = 1.0
min-train-nodes = 6
min-evaluate-nodes = 6
local-epochs = 1
learning-rate = 0.01
batch-size = 32
strategy = "FedAvgM"
distribution = "C4"
experiment-name = "FedAvgM_C4_npy"
num-clients = 6
data-source = "npy"
server-momentum = 0.9
