# Test Dirichlet(0.1) - Very non-IID with pre-partitioned .npy data - 10 rounds
num-server-rounds = 500
fraction-train = 1.0
fraction-evaluate = 1.0
min-train-nodes = 6
min-evaluate-nodes = 6
local-epochs = 1
learning-rate = 0.01
batch-size = 64
strategy = "FedAvg"
distribution = "Dir0.1"
experiment-name = "test_Dir0.1_npy"
num-clients = 6
data-source = "npy"
