# Test Label Skew C1 (1 class per client) - 10 rounds
num-server-rounds = 3
fraction-train = 1.0
fraction-evaluate = 1.0
min-train-nodes = 6
min-evaluate-nodes = 6
local-epochs = 1
learning-rate = 0.01
batch-size = 32
strategy = "FedAvg"
distribution = "C1"
experiment-name = "test_C1"
num-clients = 6
